// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL2_4sEhmY4M2ZsaG2qHahdWKEjRTxTv8',
    appId: '1:910114099193:web:dbe8c012a17d3484497728',
    messagingSenderId: '910114099193',
    projectId: 'fintra-c2c3a',
    authDomain: 'fintra-c2c3a.firebaseapp.com',
    storageBucket: 'fintra-c2c3a.firebasestorage.app',
    measurementId: 'G-38SWL2CCW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdP-eWUUp9TLdNrATYUNrFc281gFFwxUA',
    appId: '1:910114099193:android:e31424d0746a6f6d497728',
    messagingSenderId: '910114099193',
    projectId: 'fintra-c2c3a',
    storageBucket: 'fintra-c2c3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz69xwj3Muvt5yDobEiJbFQQQyqrLcUUc',
    appId: '1:910114099193:ios:c7fe0138d3901dfb497728',
    messagingSenderId: '910114099193',
    projectId: 'fintra-c2c3a',
    storageBucket: 'fintra-c2c3a.firebasestorage.app',
    iosBundleId: 'com.example.fintraMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz69xwj3Muvt5yDobEiJbFQQQyqrLcUUc',
    appId: '1:910114099193:ios:c7fe0138d3901dfb497728',
    messagingSenderId: '910114099193',
    projectId: 'fintra-c2c3a',
    storageBucket: 'fintra-c2c3a.firebasestorage.app',
    iosBundleId: 'com.example.fintraMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL2_4sEhmY4M2ZsaG2qHahdWKEjRTxTv8',
    appId: '1:910114099193:web:9f4f9946808640d6497728',
    messagingSenderId: '910114099193',
    projectId: 'fintra-c2c3a',
    authDomain: 'fintra-c2c3a.firebaseapp.com',
    storageBucket: 'fintra-c2c3a.firebasestorage.app',
    measurementId: 'G-MW0FWGXGFF',
  );
}
